apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cdep-test
description: main application pipeline
serialPipeline:
  stages:
    - targetId: prod
      profiles:
        - prod
