apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: crn-test
  labels:
    cloud.googleapis.com/location: asia-south1
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing 
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/network-interfaces: '[{"network":"vpc-goa-smartforce-prod-01","subnetwork":"sb-prod-as1-goa-cr-node"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/prj-prod-goa-smartforce-86/artifact-test/php-app-01:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "4000m"
            memory: 8Gi
      serviceAccountName: sa-goa-node-01@prj-prod-goa-smartforce-86.iam.gserviceaccount.com
